### ISSUE TITLE
Request for hardware requirements and training cost, etc

### ISSUE THREAD

**Issue by purefire** [allenai/OLMo#431]
Hi, OLMo seems to be a promising project for my research project. I'm not sure, but as I searched, I couldn't find information about the specific hardware requirements (CPU, GPU, and memory/VRAM), the training time for this model.
So Can we improve the README file regarding:
What is the minimum and recommended CPU/GPU configuration for CPU/GPU requirements? And what about memory/VRAM?
How long does it take to train on a typical dataset?
And should I be aware of any specific hardware configurations or software dependencies for optimal performance?
Any information would be greatly appreciated.
Thank you.

**Comment by epwalsh** [comment]
Hey @purefire, it's hard to give specific answers to some of these questions since training code is flexible enough to work on a wide variety of hardware configurations, yet the training speed will vary drastically between environments depending on # of GPUs, GPU memory, interconnect, etc. I'll try my best to answer these:

> What is the minimum and recommended CPU/GPU configuration for CPU/GPU requirements? And what about memory/VRAM?

Our training code is hardcoded for multiple GPUs, so you'll need at least 2. The more the better of course. Fewer GPUs means you get less memory savings from FSDP, so (for the 7B at least) you'll need to configure other memory-saving options like activation checkpointing, which will cost you some speed. The hardware section in [the paper](https://allenai.org/olmo/olmo-paper.pdf) describes the two different cluster configurations we used for the official runs, but we successfully trained on much fewer GPUs as well.

> How long does it take to train on a typical dataset?

Depends. On 216x 40GB A100 GPUs with 800Gbps interconnect, we achieved an average of 2,500 tokens per second per GPU during training. So if you have a similar hardware stack you can expect similar speed.

> And should I be aware of any specific hardware configurations or software dependencies for optimal performance?

For hardware, fast interconnect is very important. On the software side there's no special dependencies, just PyTorch.

**Comment by austinmw** [comment]
Hi @epwalsh , can the 7B model be trained with 8 A100 GPUs without requiring other memory-savings options?

And if I do the math on that, is that:
2,500,000,000 tokens / 2,500 tokens per second per GPU = 1,000,000 seconds / 8 GPU = 125,000 / 3600 = ~35 hours
And for a very rough cost estimate, at  Amazon p4d.24xlarge on-demand pricing of $32.77/hr, a total of around $1,200.00?
Just want to double check that I'm in the right ball park here.

**Comment by epwalsh** [comment]
@austinmw I'm not 100% certain on this, but I think you could probably train the 7B on 8 A100 GPUs with the following flags / config options for memory savings:

```bash
torchrun ... config.yaml \
  --fsdp.wrapping_strategy=by_block_and_size \
  --activation_checkpointing=fine_grained \
  --device_train_microbatch_size=1
```

If you get OOM with that you could also try `--activation_checkpointing=whole_layer`.

These settings will affect throughput, so you might not get 2,500tps.

**Comment by austinmw** [comment]
Thanks!

**Comment by austinmw** [comment]
Oh also, curious if you happen to know the throughput in tokens per second per GPU for the 65B model that is currently in progress?

**Comment by epwalsh** [comment]
Looks like we're averaging about 80tps per GPU right now.

**Comment by austinmw** [comment]
Thanks! Sorry one last question, I didn't see in W&B logs, what was the total time to train 2.5T tokens for 7B model on the 216 GPUs?

**Comment by epwalsh** [comment]
@austinmw about ~50 days.

**Comment by prakamya-mishra** [comment]
@epwalsh thank you for answering the above questions. What throughput did you experience while training OLMo-1B on a single node for the following settings:
- MI250
    - without flash-attention
    - with flash-attention
- A100
    - without flash-attention
    - with flash-attention
Also some idea regarding the batch-size would be great for fair compression with the 32 node training and 1 node training. Thanks!

**Comment by dumitrac** [comment]
I apologize for our delay in response. In order to help surface current, unresolved issues, we are closing tickets prior to February 29.
Please reopen your ticket if you are continuing to experience this issue.
Thank you!

**Comment by prakamya-mishra** [comment]
> @epwalsh thank you for answering the above questions. What throughput did you experience while training OLMo-1B on a single node for the following settings:
> 
> * MI250
>   
>   * without flash-attention
>   * with flash-attention
> * A100
>   
>   * without flash-attention
>   * with flash-attention
> 
> Also some idea regarding the batch-size would be great for fair compression with the 32 node training and 1 node training. Thanks!

@dumitrac can you share some info regarding this?

**Comment by dumitrac** [comment]
@prakamya-mishra - MI250 about 6k tokens per device per second, A100 18k tokens per device per second.
These are on 16 nodes for M250, and 8 nodes for A100.
We don't use flash attention for MI250, and use it for A100.
