### ISSUE TITLE
TypeError - running example code 

### ISSUE THREAD

**Issue by KPK101** [allenai/OLMo#743]
### 🐛 Describe the bug

The model being used: 'allenai/Molmo-7B-O-0924'

I faced issues with the source code (example script) giving errors. 
```
File ~/.cache/huggingface/modules/transformers_modules/allenai/Molmo-7B-O-0924/d8572c4c53238d9c21294233e02770393befaa8a/modeling_molmo.py:1343, in OLMoPretrainedVisionBackbone.encode_image(self, images)
   1340 v_cfg = self.config.vision_backbone
   1341 B, T, N, D = images.shape
-> 1343 mask = ~torch.all(images.view(B * T, N, D) == -1, dim=(1, 2), keepdim=True)
   1345 # Output all hidden states
   1346 # n_layers x (batch_num_crops, (1+)n_tokens, image_emb_dim)
   1347 images = images.view(B * T, N, D)

TypeError: all() received an invalid combination of arguments - got (Tensor, keepdim=bool, dim=tuple), but expected one of:
 * (Tensor input, *, Tensor out)
      didn't match because some of the keywords were incorrect: keepdim, dim
 * (Tensor input, int dim, bool keepdim, *, Tensor out)
 * (Tensor input, name dim, bool keepdim, *, Tensor out)
```
Faced the same issue with other models as well.

### Versions

Python 3.10.15

**Comment by aman-17** [comment]
Hello @KPK101, It might be better to open an issue directly on the model’s Hugging Face page [here](https://huggingface.co/allenai/Molmo-7B-O-0924).
From what you’ve shared, I’m assuming the error arises due to the function `torch.all()` is being called with arguments that don’t match its expected signature. `dim=(1, 2)` is passed as a tuple, but `torch.all()` expects `dim` to be a single integer.
